apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capacity-review.fullname" . }}
  labels:
    {{- include "capacity-review.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "jwtSecret is required" .Values.jwtSecret | quote }}
